<h1>Cadastrar Produtos</h1>

<form action="<?php echo $this->baseUrl('produto/gravar'); ?>" method="post" enctype="multipart/form-data">
	<input type="hidden" name="id_produto" value="<?php echo $this->row['id_produto']; ?>" />
	
	<div class="form-group">
	    <label for="nome">Nome</label>
	    <input type="text" class="form-control" id="nome" name="nome" value="<?php echo $this->row['nome']; ?>">
	</div>
    
    <div class="form-group">
	    <label for="preco">Preço</label>
	    <input type="text" class="form-control" id="preco" name="preco" value="<?php echo $this->row['preco']; ?>">
	</div>
    
    <div class="form-group">
	    <label for="codigo">Codigo</label>
	    <input type="text" class="form-control" id="codigo" name="codigo" value="<?php echo $this->row['codigo']; ?>">
	</div>
    
    <div class="form-group">
	    <label for="marca">Marca</label>
	    <input type="text" class="form-control" id="marca" name="marca" value="<?php echo $this->row['marca']; ?>">
	</div>
    
    <div class="form-group">
	    <label for="altura">Altura</label>
	    <input type="text" class="form-control" id="altura" name="altura" value="<?php echo $this->row['altura']; ?>">
	</div>
    
    <div class="form-group">
	    <label for="diametro">Diametro</label>
	    <input type="text" class="form-control" id="diametro" name="diametro" value="<?php echo $this->row['diametro']; ?>">
	</div>
    
    <div class="form-group">
	    <label for="cor">Cor</label>
    	<select class="form-control" id="cor" name="cor">
    		<option value="Sem cor">Selecione</option>
            <option selected="selected" value="<?php echo $this->$row['cor']; ?>"> <?php echo $this->row['cor']; ?></option>
            <option value="Azul"> Azul </option>
            <option value="Amarelo"> Amarelo </option>
            <option value="Cereja"> Cereja </option>
            <option value="Vinho"> Vinho </option>
            <option value="Vermelho"> Vermelho </option>
            <option value="Roxo"> Roxo </option>
            <option value="Cinza"> Cinza </option>
            <option value="Preto"> Preto </option>
            <option value="Rosa"> Rosa </option>
            <option value="Verde"> Verde </option>
    		
    	</select>
	</div>
    
    <div class="form-group">
	    <label for="espessura">Espessura</label>
	    <input type="text" class="form-control" id="espessura" name="espessura" value="<?php echo $this->row['espessura']; ?>">
	</div>
    
    

   
    
      <div class="form-group">
	    <label for="id_linha">Linha</label>
          <div id="linha"> 
    	<select class="form-control" id="id_linha" name="id_linha">
    		<option value="">Selecione</option>
    		<?php foreach($this->rowSetLinha as $rowLinha){ ?>
    			<option <?php echo $this->row['linha_id_linha'] == $rowLinha['id_linha'] ? 'selected="selected"' : ''; ?> value="<?php echo $rowLinha['id_linha']; ?>"><?php echo $rowLinha['nome']; ?></option>
    		<?php } ?>
    	</select>
        </div>
	</div>
    
    <div class="form-group">
	    <label for="tipo">Tipo</label>
        <div id="div_tipos">        
    	   <select class="form-control" id="tipo_id_tipo" name="tipo_id_tipo">
    		  <option value="">Selecione</option>
    		      <?php foreach($this->rowSetTipo as $rowTipo){ ?>
                <option <?php echo $this->row['tipo_id_tipo'] == $rowTipo['id_tipo'] ? 'selected="selected"' : ''; ?> value="<?php echo $rowTipo['id_tipo']; ?>"><?php echo $rowTipo['nome']; ?></option>
    		      <?php } ?>
    	   </select>
        </div>
	</div>

    </select>


	<div class="text-center">
		<input type="submit" value="Enviar" class="btn btn-success" />
		<a href="<?php echo $this->baseUrl('produto/pesquisar'); ?>" class="btn btn-danger" >Voltar</a>
	</div>
</form>

<script>

    $(function(){  
          
        $('#id_linha').change(function(){
            $('#div_tipos').load('<?php echo $this->baseUrl('produto/carregar-tipo/id_linha/'); ?>'+ $('#id_linha').val());
        });
    });

</script>