<h1>Cadastrar Produtos</h1>

<h2>Página em construção</h2>

<form action="<?php echo $this->baseUrl('produto/gravar'); ?>" method="post" enctype="multipart/form-data">
	<input type="hidden" name="id_produto" value="<?php echo $this->row['id_produto']; ?>" />
	
	<div class="form-group">
	    <label for="nome">Nome</label>
	    <input type="text" class="form-control" id="nome" name="nome" value="<?php echo $this->row['nome']; ?>">
	</div>
    
    <div class="form-group">
	    <label for="preco">Preço</label>
	    <input type="text" class="form-control" id="preco" name="preco" value="<?php echo $this->row['preco']; ?>">
	</div>
    
    <div class="form-group">
	    <label for="codigo">Codigo</label>
	    <input type="text" class="form-control" id="codigo" name="codigo" value="<?php echo $this->row['codigo']; ?>">
	</div>
    
    <div class="form-group">
	    <label for="marca">Marca</label>
	    <input type="text" class="form-control" id="marca" name="marca" value="<?php echo $this->row['marca']; ?>">
	</div>
    
    <div class="form-group">
	    <label for="altura">Altura</label>
	    <input type="text" class="form-control" id="altura" name="altura" value="<?php echo $this->row['altura']; ?>">
	</div>
    
    <div class="form-group">
	    <label for="diametro">Diametro</label>
	    <input type="text" class="form-control" id="diametro" name="diametro" value="<?php echo $this->row['diametro']; ?>">
	</div>
    
    <div class="form-group">
	    <label for="cor">Cor</label>
	    <input type="text" class="form-control" id="cor" name="cor" value="<?php echo $this->row['cor']; ?>">
	</div>
    
    <div class="form-group">
	    <label for="espessura">Espessura</label>
	    <input type="text" class="form-control" id="espessura" name="espessura" value="<?php echo $this->row['espessura']; ?>">
	</div>
    
    <div class="form-group">
	    <label for="tipo_id_tipo">Tipo</label>
	    <input type="text" class="form-control" id="tipo_id_tipo" name="tipo_id_tipo" value="<?php echo $this->row['tipo_id_tipo']; ?>">
        
    
	</div>
    
    <div class="form-group">
	    <label for="foto">Foto</label>
	    <input type="file" class="form-control" id="foto" name="foto" value="<?php echo $this->row['foto']; ?>">
	</div>
	
	<div class="text-center">
		<input type="submit" value="Enviar" class="btn btn-success" />
		<a href="<?php echo $this->baseUrl('usuario/index'); ?>" class="btn btn-danger" >Voltar</a>
	</div>
</form>

<script>

    $(function(){  
          
        $('#id_uf').change(function(){
            $('#div_municipios').load('<?php echo $this->baseUrl('usuario/carregar-municipio/id_uf/'); ?>'+ $('#id_uf').val());
        });
    });

</script>