<h1>Listagem de Produtos</h1>

<a href="<?php echo $this->baseUrl('produto/formulario'); ?>" >Inserir</a>

<table class="table table-striped">
	
    <thead>
      <tr>  
        <th>Nome</th>
        <th>Preço</th>
        <th>Código</th>
        <th>Marca</th>
        <th>Altura</th>
        <th>Diametro</th>
        <th>Cor</th>
        <th>Espessura</th>
        <th>Tipo</th>
        <th>Ações</th>
      </tr>
    </thead>

	<?php foreach($this->rowSet as $row){ ?>
       <tr>
         <td><?php echo $row['nome']; ?></td>
         <td><?php echo $row['preco']; ?></td>
         <td><?php echo $row['codigo']; ?></td>
         <td><?php echo $row['marca']; ?></td>
         <td><?php echo $row['altura']; ?></td>
         <td><?php echo $row['diametro']; ?></td>
         <td><?php echo $row['cor']; ?></td>
         <td><?php echo $row['espessura']; ?></td>
         <td><?php echo $row['tipo_id_tipo']; ?></td>
         <td>
             <a title="ADD FOTO" class="btn btn-primary" href="<?php echo $this->baseUrl('produto/upload/id_produto/' . $row['id_produto']); ?>" ><span class="glyphicon glyphicon-camera"></span></a>
             <a title="ALTERAR" class="btn btn-info" href="<?php echo $this->baseUrl('produto/formulario/id_produto/' . $row['id_produto']); ?>" ><span class="glyphicon glyphicon-pencil">  </span></a>
             <a title="EXCLUIR" class="btn btn-danger" href="<?php echo $this->baseUrl('produto/excluir/id_produto/' . $row['id_produto']); ?>" ><span class="glyphicon glyphicon-trash"></span></a>
              
        </td>
       </tr>
	<?php } ?>
    
</table>