
<form method="post" enctype="multipart/form-data" action="<?php echo $this->baseUrl('produto/salvar'); ?>">

<div class="form-group">
        <input type="hidden" value="<?php echo $this->id_produto; ?>" name="produto_id_produto" />
	    <label for="foto">Foto</label>
	    <input type="file" class="form-control" id="foto" name="foto"  value="<?php echo $this->row['foto']; ?>">
</div>

<div class="text-center">
		<input type="submit" value="Enviar" class="btn btn-success" />
		<a href="<?php echo $this->baseUrl('usuario/index'); ?>" class="btn btn-danger" >Voltar</a>
	</div>
</form>