<h1>Usuário</h1>

<form action="<?php echo $this->baseUrl('usuario/gravar'); ?>" method="post" >
    
    <input type="hidden" class="form-control" id="id_usuario" name="id_usuario" value="<?php echo $this->row['id_usuario']; ?>">
    
    <div id="tentativa" style="width:50%">  
        
        <div class="form-group">
            <label for="nome">Nome</label>
            <input type="text" class="form-control" id="nome" name="nome" value="<?php echo $this->row['nome']; ?>">
        </div>
        
        <div class="form-group">
            <label for="telefone">Telefone</label>
            <input type="text" class="form-control" id="telefone" name="telefone" value="<?php echo $this->row['telefone']; ?>">
	    </div>

	</div>
	
    <div id="tentativa" style="width:50%"> 
        
         <div class="form-group">
            <label for="email">E-mail</label>
            <input type="text" class="form-control" id="email" name="email" value="<?php echo $this->row['email']; ?>">
	    </div>
        
        <div class="form-group">
	       <label for="senha">Senha</label>
	       <input type="password" class="form-control" id="senha" name="senha" value="<?php echo $this->row['senha']; ?>">
	    </div>
        
    </div>
	
	 
	 <div class="text-center">
		<input type="submit" value="Enviar" class="btn btn-success" />
		<a href="<?php echo $this->baseUrl('usuario/listagem'); ?>" class="btn btn-danger" >Voltar</a>
	</div>
	
	
	
	
</form>

