<h1>Login</h1>

<?php if(!empty($_SESSION['mensagem'])){

    
    echo '<div class="alert alert-warning">
  <strong>Atenção! ';
    echo $_SESSION['mensagem'];
    echo '</strong> </div>';
    unset($_SESSION['mensagem']);

}?>

<form action="<?php echo $this->baseUrl('usuario/autenticar'); ?>" method="post" enctype="multipart/form-data">
	<input type="hidden" name="id_usuario" value="<?php echo $this->row['id_usuario']; ?>" />
	


	<div class="form-group">
	    <label for="email">E-mail</label>
	    <input type="text" class="form-control" id="email" name="email" value="<?php echo $this->row['email']; ?>">
	</div>
	
	<div class="form-group">
	    <label for="senha">Senha</label>
	    <input type="password" class="form-control" id="senha" name="senha" value="<?php echo $this->row['senha']; ?>">
	</div>
    
	<div class="text-center">
		<input type="submit" value="Enviar" class="btn btn-success" />
		<a href="<?php echo $this->baseUrl('usuario/index'); ?>" class="btn btn-danger" >Voltar</a>
	</div>
</form>

<script>

    $(function(){  
          
        $('#id_uf').change(function(){
            $('#div_municipios').load('<?php echo $this->baseUrl('usuario/carregar-municipio/id_uf/'); ?>'+ $('#id_uf').val());
        });
    });

</script>