<h1>Formulario</h1>

<form action="<?php echo $this->baseUrl('cliente/gravar'); ?>" method="post">
	
	
	<div class="form-group">
	    <label for="nome">Nome do Cliente: </label>
	    <input type="text" class="form-control" id="nome" name="nome">
	</div>
	
	<div class="form-group">
	    <label for="codigo">Codigo: </label>
	    <input type="text" class="form-control" id="codigo" name="codigo">
	</div>
	
	<div class="form-group">
	    <label for="cpf">CPF: </label>
	    <input type="text" class="form-control" id="cpf" name="cpf">
	</div>
	
	<div class="form-group">
	    <label for="nascimento">Data de Nascimento: </label>
	    <input type="date" class="form-control" id="data" name="data">
	</div>
    
    <div class="form-group">
	    <label for="endereco">Endereço: </label>
	    <input type="text" class="form-control" id="endereco" name="endereco">
	</div>
    
    <div class="form-group">
	    <label for="email">E-mail: </label>
	    <input type="text" class="form-control" id="email" name="email">
	</div>
    
    <div class="form-group">
	    <label for="tel1">Telefone 1: </label>
	    <input type="text" class="form-control" id="tel1" name="tel1">
	</div>
    
    <div class="form-group">
	    <label for="tel2">Telefone 2: </label>
	    <input type="text" class="form-control" id="tel2" name="tel2">
	</div>
    
    <div class="form-group">
	    <label for="tel3">Telefone 3: </label>
	    <input type="text" class="form-control" id="tel3" name="tel3">
	</div>
	
    <div class="form-group">
	    <label for="tipo">Tipo: </label>
	    <input type="text" class="form-control" id="tipo" name="tipo">
	</div>
    
	<div class="text-center">
		<input type="submit" value="Enviar" class="btn btn-success" />
		<a href="<?php echo $this->baseUrl('cliente/listar'); ?>" class="btn btn-danger" >Voltar</a>
	</div>
</form>