<h1>Formulario</h1>

<form action="<?php echo $this->baseUrl('cliente/gravar'); ?>" method="post">
	
	
	  
	    <input type="hidden" type="text"   name="id_clientes" value="<?php echo $this->row['id_clientes']; ?>">
	
    
    
	<div class="form-group">
	    <label for="nome">Nome do Cliente: </label>
	    <input type="text" class="form-control" id="nome" name="nome" value="<?php echo $this->row['nome']; ?>">
	</div>
    
    
	
	<!--<div class="form-group">
	    <label for="codigo">Codigo: </label>
	    <input type="number" class="form-control" id="codigo" name="codigo">
	</div>-->
	
	<div class="form-group">
	    <label for="cpf">CPF: </label>
	    <input type="text" class="form-control" id="cpf" name="cpf" value="<?php echo $this->row['cpf']; ?>">
	</div>
	
	<div class="form-group">
	    <label for="data_nascimento">Data de Nascimento: </label>
	    <input type="date" class="form-control" id="data_nascimento" name="data_nascimento" value="<?php echo $this->row['data_nascimento']; ?>">
	</div>
    
    <div class="form-group">
	    <label for="endereco">Endereço: </label>
	    <input type="text" class="form-control" id="endereco" name="endereco" value="<?php echo $this->row['endereco']; ?>">
	</div>
    
    <div class="form-group">
	    <label for="email">E-mail: </label>
	    <input type="text" class="form-control" id="email" name="email" value="<?php echo $this->row['email']; ?>">
	</div>
    
    <div class="form-group">
	    <label for="tel1">Telefone 1: </label>
	    <input type="text" class="form-control" id="tel1" name="tel1" value="<?php echo $this->row['tel1']; ?>">
	</div>
    
    <div class="form-group">
	    <label for="tel2">Telefone 2: </label>
	    <input type="text" class="form-control" id="tel2" name="tel2" value="<?php echo $this->row['tel2']; ?>">
	</div>
    
    <div class="form-group">
	    <label for="tel3">Telefone 3: </label>
	    <input type="text" class="form-control" id="tel3" name="tel3" value="<?php echo $this->row['tel3']; ?>">
	</div>
	
    <div class="form-group">
	    <label for="cliente_tipo">Tipo: </label>
	    <input type="text" class="form-control" id="cliente_tipo" name="cliente_tipo" value="<?php echo $this->row['cliente_tipo']; ?>">
	</div>
    
	<div class="text-center">
		<input type="submit" value="Enviar" class="btn btn-success" />
		<a href="<?php echo $this->baseUrl('cliente/listar'); ?>" class="btn btn-danger" >Voltar</a>
	</div>
</form>