<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8" />
    <title>Compras</title>

    <link href="<?php echo $this->baseUrl('js/bootstrap/css/bootstrap.min.css'); ?>" rel="stylesheet">

    <!-- Mainly scripts -->
    <script src="<?php echo $this->baseUrl('js/jquery-2.2.3.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('js/bootstrap/js/bootstrap.min.js'); ?>"></script>

    <?php echo $this->headScript(); ?>
    
       
    <style> 
        .navbar-inverse {
            background-color: #b71c1c ;
            border-color: #080808;          
            <?php echo $this->headScript(); ?>}
            
        #tentativa{  
            float: left;
            background-color:#ffffff;  
            width:206px;  
            height:200px;  
        }
        
        #direita{
            margin-left: 206px;
            background-color:#00FF66;  
            height:1000px;  
        }
    </style>
    
</head>

<body>

 <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Tabela Real</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            
            <li><a href="<?php echo $this->baseUrl('produto/pesquisar'); ?>">Pesquisar Produtos</a></li>
            <li><a href="<?php echo $this->baseUrl('produto/formulario'); ?>">Cadastrar Produtos</a></li>
            <li><a href="<?php echo $this->baseUrl('cliente/listar'); ?>">Listar Clientes</a></li>
            <li><a href="<?php echo $this->baseUrl('cliente/formulario'); ?>">Cadastrar Clientes</a></li>
            <li><a href="<?php echo $this->baseUrl('usuario/listar'); ?>">Listar Usuários</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="<?php echo $this->baseUrl('usuario/formulario'); ?>"><span class="glyphicon glyphicon-user"></span> Cadastrar</a></li>
            <li><a href="<?php echo $this->baseUrl('usuario/login'); ?>"><span class="glyphicon glyphicon-log-in"></span> Login</a>     
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
	
	<div class="container"  style="margin-top: 60px;">
    	<?php echo $this->layout()->content; ?>
	</div>
</body>
</html>
